#!/bin/sh
set -a
. ./root.env
set +a
CN=$ROOTCN
DN="/C=$C/ST=$ST/L=$L/O=$O/OU=$OU/CN=$CN/emailAddress=$MAIL"
echo "-----------------------------"
echo "Create Root CA"
echo "-----------------------------"
cd $ROOTCA_DIRECTORY
mkdir certs crl newcerts private
chmod 700 private
touch index.txt
echo 1000 > serial
openssl genrsa -aes256 -passout env:ROOTCA_PASSPHRASE -out private/ca.key.pem 4096
chmod 400 private/ca.key.pem
openssl req -config ../root-openssl.cnf \
      -key private/ca.key.pem \
      -passin env:ROOTCA_PASSPHRASE \
      -new -x509 -days 3650 -sha256 -extensions v3_ca \
      -out certs/ca.cert.pem \
      -subj "$DN"
echo "Created Root Certificate"
chmod 444 certs/ca.cert.pem
