#!/bin/sh
set -e
umask 077
if [ $# -ne 1 ] ; then
    echo 'revoke_cert <CN>'
    echo 'revoke_cert ftp.example.com'
    exit 1
fi
echo "-----------------------------"
echo "Revoking Intermediate CA Certificate for $1"
echo "-----------------------------"
cd $INTERMEDIATECA_DIRECTORY
openssl ca -config ../intermediate-openssl.cnf \
      -passin env:INTERMEDIATECA_PASSPHRASE \
      -revoke certs/$1.cert.pem
