#!/bin/sh
if [[ $# -ne 1 ]] ; then
    echo 'start_ocsp_server <OCSP Server DN>'
    echo 'start_ocsp_server ocsp.example.com'        
    exit 1
fi
echo "-----------------------------"
echo "Starting OCSP Server $1"
echo "-----------------------------"
cd $INTERMEDIATECA_DIRECTORY
##      -passin env:INTERMEDIATECA_PASSPHRASE \
openssl ocsp -port $OCSP_PORT \
      -index index.txt \
      -CA certs/ca-chain.cert.pem \
      -rkey private/$1.key.pem \
      -rsigner certs/$1.cert.pem \
      -nrequest 1			# -text
